apiVersion: v2
name: edger
description: Helm chart for EdgeR, a stateless Rust runtime for JS and WASM workers
type: application
version: 0.2.0
appVersion: "0.2.0"
keywords:
  - edger
  - edge-runtime
  - deno
  - rust
  - workers
home: https://github.com/djalmajr/edger
sources:
  - https://github.com/djalmajr/edger
maintainers:
  - name: Djalma Junior
    email: noreply@djalmajr.dev
