{{- if .Values.rootKey.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edger.rootKeySecretName" . }}
  labels:
    {{- include "edger.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.rootKey.secretKey | quote }}: {{ .Values.rootKey.value | quote }}
{{- end }}
